[package]
name = "git-twig"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
anyhow = "1.0"
image = "0.25.9"
ratatui = "0.26"
crossterm = "0.27"
ansi-to-tui = "3.1"
